var tweets = [];
var incre=2;
function mypost()
{
	var div=document.createElement("DIV");
	div.className="mainpost";
	var parent=document.getElementsByClassName("allpost");
	parent[0].insertBefore(div, parent[0].childNodes[0]);
	var div1=document.createElement("DIV");
	div1.className="userimg";
	var img=document.createElement("img");
	img.src="upload.png";
	div1.appendChild(img);
	div.appendChild(div1);
	var div2=document.createElement("DIV");
	div2.className="username";
	var para=document.createElement("p");
	para.className="name";
	var text1=document.createTextNode("Ameer Eyad");
	para.appendChild(text1);
	div2.appendChild(para);
	div.appendChild(div2);
	var para2=document.createElement("p");
	para2.className="quotes";
	para2.id="quotes"+incre;
	var pararec=document.getElementById("mypara");
	var tweet ={userName:"Ameer Eyad",tweet: pararec.value};
	tweets.push(tweet);
	console.log(tweets);
	var paapa=pararec.value.replace(/\s/g, "\u00a0");
	pararec.value="";
	var text2=document.createTextNode(paapa);
	para2.appendChild(text2);
	div.appendChild(para2);
	var div3=document.createElement("DIV");
	div3.className="likedislike";
	var span1=document.createElement("span");
	span1.className="fa fa-heart";
	span1.id="heart"+incre;
	var span2=document.createElement("span");
	span2.className="fa fa-retweet";
	span2.id="retweet"+incre;
	var fun1="redheart"+"("+"'"+span1.id+"'"+");";
	span1.setAttribute("onClick",fun1);
	var fun2="greenretweet"+"("+"'"+span2.id+"'"+","+"'"+para2.id+"'"+");";
	span2.setAttribute("onClick",fun2);
	div3.appendChild(span1);
	div3.appendChild(span2);
	div.appendChild(div3);
	incre ++;
}
function redheart(heart)
{
    var red_heart=document.getElementById(heart);
    red_heart.style.color = "red";
}
function greenretweet(retweet,tweet_text)
{
	var green_retweet=document.getElementById(retweet);  
	green_retweet.style.color="green";
	var div=document.createElement("DIV");
	div.className="mainpost";
	var parent=document.getElementsByClassName("allpost");
	parent[0].insertBefore(div, parent[0].childNodes[0]);
	var span=document.createElement("span");
	span.className="fa fa-retweet";
	div.appendChild(span);
	var text=document.createTextNode("Ameer Eyad");
	div.appendChild(text);
	var div1=document.createElement("DIV");
	div1.className="userimg";
	var img=document.createElement("img");
	img.src="upload.png";
	div1.appendChild(img);
	div.appendChild(div1);
	var div2=document.createElement("DIV");
	div2.className="username";
	var para=document.createElement("p");
	para.className="name";
	var text1=document.createTextNode("Ameer Eyad");
	para.appendChild(text1);
	div2.appendChild(para);
	div.appendChild(div2);
	var para2=document.createElement("p");
	para2.className="quotes";
	para2.id="quotes"+incre;
	var pararec=document.getElementById(tweet_text).innerHTML;
	var text2=document.createTextNode(pararec);
	para2.appendChild(text2);
	div.appendChild(para2);
	var div3=document.createElement("DIV");
	div3.className="likedislike";
	var span1=document.createElement("span");
	span1.className="fa fa-heart";
	span1.id="heart"+incre;
	var span2=document.createElement("span");
	span2.className="fa fa-retweet";
	span2.id="retweet"+incre;
	var fun1="redheart"+"("+"'"+span1.id+"'"+");";
	span1.setAttribute("onClick",fun1);
	var fun2="greenretweet"+"("+"'"+span2.id+"'"+","+"'"+para2.id+"'"+");";
	span2.setAttribute("onClick",fun2);
	div3.appendChild(span1);
	div3.appendChild(span2);
	div.appendChild(div3);
	var tweet ={userName:"Ameer Eyad",tweet: document.getElementById(tweet_text).innerHTML};
	console.log(tweets);
	tweets.push(tweet);
	incre ++;
}
